### ISSUE TITLE
Add some missing Elro products to the app

### ISSUE THREAD

**Issue by RobNoot** [athombv/eu.elro#1]
Current Euro app is missing all their 433Mhz wireless doorbell types.
I have for example type DB230 which i would like to see added in the app.
If there is any way i can help than please let me know.

**Comment by tlangelaar** [comment]
I have a doorbell button (433,92) that doesn't have any names on it. But it working together with the Elro DB200 and DB260 doorbell receivers. I've recorded (Developers portal Athom) a couple of presses on the doorbell button. Does this help in updating the driver?
[Doorbell for Elro DB200.vcd.log](https://github.com/athombv/eu.elro/files/1527387/Doorbell.for.Elro.DB200.vcd.log)

**Comment by htilburgs** [comment]
Is this Issue still actual?

+1 for adding the 433Mhz wireless doorbell types.
I'm using a DB250, which I would like to see in the App so I can use it with Homey.

**Comment by RobNoot** [comment]
For me the question is still actual.
If i can help by , for example, provide you with my own doorbell for developing.... Please let me know and i will see what i can arrange.

+1  for enhancement of the Elro app with doorbells !

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2607
