### ISSUE TITLE
Add support for AB600S

### ISSUE THREAD

**Issue by nielsvdc** [athombv/eu.elro#2]
Can you add support for Elro AB600S switches? They have 2 codewheels 1-16 and A-P. Thanks

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
