### ISSUE TITLE
ELRO AB440R not recognized, AB440SC work

### ISSUE THREAD

**Issue by eelco2k** [athombv/eu.elro#3]
When i want to add the Elro AB440R and push a button for pairing it does not recognize it.

i can pair every AB440SC wall socket individual  but i cannot use my remote in conjunction with homey because the signals get "stuck". when i do use the remote control the led dims rapid like the battery is almost dead. I then have to restart homey, and unplug the wall sockets and then after a while i can use the remote control back again. but whenever i use homey to switch on/off the wall sockets again the remote control doesn't work anymore and the same behavior as described above is happening.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
